@$ORACLE_HOME/javavm/install/initjvm.sql
@$ORACLE_HOME/oracore/admin/initxml.sql
@$ORACLE_HOME/rdbms/admin/catxsu.sql
@$ORACLE_HOME/javavm/install/init_jis.sql
@$ORACLE_HOME/javavm/install/jisja.sql
@$ORACLE_HOME/javavm/install/jisaephc.sql
@$ORACLE_HOME/rdbms/admin/initplgs.sql
@$ORACLE_HOME/jsp/install/initjsp.sql
@$ORACLE_HOME/jsp/install/jspja.sql
@$ORACLE_HOME/rdbms/admin/initplsj.sql
@$ORACLE_HOME/rdbms/admin/initjms.sql
@$ORACLE_HOME/rdbms/admin/initrepapi.sql
@$ORACLE_HOME/rdbms/admin/initsoxx.sql
