set echo on
show parameter compatible
show parameter db_block_buffers
show parameter db_cache_size
show parameter log_checkpoint_interval
show parameter optimizer_mode
show parameter shared_pool_size
show parameter sort_area_size
show parameter pga_aggregate_target
show parameter job_queue_processes
set echo off
